const D='Designed an interactive and engaging educational platform aimed at improving online learning experiences. This included developing intuitive navigation, interactive course materials, and features that support student engagement and participation, making learning more accessible and enjoyable.'
export const STATS=[['12','Year of','Experience'],['250','Projects','Completed'],['680','Satisfied','Happy Clients'],['18','Awards','Won Received']]
export const OFFER=[['UI/UX Design','Designing visually appealing and user-friendly interfaces that captivate and retain users.'],['Mobile App Design','Designing intuitive and appealing mobile applications for both iOS and Android platforms.'],['Brand Identity Design','Developing cohesive visual branding that resonates with your audience and sets you apart.'],['Web Development','Crafting responsive and engaging websites that align with both user needs and goals.']]
export const TABS=['All Projects','Branding','Web Design','UI/UX','App Dev']
export const WORKS=[['Photo App UI/UX','UI/UX','Web Design'],['Mobile App Design','App Dev','Branding'],['Interaction Design','UI/UX','Web Design'],['Design Consultation','Branding','UI/UX']]
export const RESUME={Education:[['2018-2019','Certification in UX Design','University of Stanford','4.9'],['2017-2018','Certification in Web Dev','University of Stanford','5.0'],['2016-2018','Advanced UX/UI Bootcamp','Design Academy','4.9'],['2015-2016','Certification in Graphic Design','Coursera','4.8']],Experience:[['2019 - Present','Senior UI/UX Designer','Leader in Creative team',''],['2018 - 2019','UI/UX Designer at BOS Agency','Tech Startup',''],['2016 - 2018','Freelance UI/UX Designer','Self-Employed',''],['2015 - 2016','Junior UI Designer','Web Solutions Team','']]}
export const SKILLS=[['Figma',98],['Adobe XD',82],['Illustrator',76],['Sketch',58],['Photoshop',60],['Webflow',72],['Framer',93]]
export const SERVICES=[
['UI/UX Design',[['User Research','Conducting thorough user research through surveys, interviews, and usability studies to understand target audiences and their needs, ensuring designs are user-centric and effective.'],['Wireframing and Prototyping','Designing detailed wireframes and interactive prototypes to visualize and test user flows and interactions, allowing for early feedback and iterative improvements.'],['User Testing','Implementing comprehensive user testing sessions to gather feedback, identify pain points, and make data-driven design improvements to ensure a seamless user experience.']]],
['Mobile App Design',[['Cross-platform Design','Creating designs that work smoothly on both iOS and Android platforms, ensuring a consistent and high-quality user experience regardless of the device.'],['Interactive Prototypes','Developing interactive prototypes to demonstrate app functionality, allowing stakeholders to experience the app before development begins.'],['Consistent Branding','Ensuring the app design is consistent with your brand\'s identity and aesthetics, maintaining brand recognition and trust across all touchpoints.']]],
['Brand Identity Design',[['Logo Design','Creating memorable and impactful logos that represent your brand\'s essence and values, helping you stand out in a crowded marketplace.'],['Brand Guidelines','Developing comprehensive brand guidelines that include typography, color and visual styles to maintain consistency across all platforms and media.'],['Visual Assets:','Designing a variety of visual assets, including business cards, letterheads, to ensure all brand communications are professional and cohesive.']]],
['Web Development',[['Front-end Development','Utilizing modern technologies like HTML, CSS, and JavaScript to create responsive and interactive web pages that provide an engaging user experience.'],['Back-end Development','Implementing server-side logic and database management with technologies such as Node.js, Python, or Ruby on Rails to ensure seamless performance and data integrity.'],['Content Management Systems','Integrating user-friendly CMS platforms like WordPress, Drupal, or custom solutions for easy content updates, allowing non-technical users to manage website content efficiently.']]]]
export const PROJECTS=[['UI/UX','E-commerce Website Redesign'],['App Design','Fitness App UI/UX'],['Web Development','Travel Booking Platform'],['Visual Design','Educational Platform UI/UX']].map(p=>[...p,D])
export const PLANS=[['Basic','49',['Require your wireframe','Design using Figma, Framer','Develop with Webflow, React, WordPress, Laravel/PHP','Remote/Online collaboration','Available on business days, no weekends','6 months of support']],['Business','99',['No wireframe needed','Design using Figma, Framer','Develop with Webflow, React, WordPress, Laravel/PHP','Remote/Online collaboration','Available on business days, no weekends','12 months of support','Your project is always a priority','Customer care gifts included']]]
export const FAQ=['What is the main focus of your portfolio?','Will you include a blog or other written content?','How much do your services cost?','How long does it take to see results?','Do you offer ongoing support?','Do you work with businesses in my industry?']
const T=[['5 UI/UX Trends to Watch in 2024','App Design'],['The Importance of User Research','Branding'],['The Role of Color Psychology','Mockup']]
export const POSTS=Array.from({length:9},(_,i)=>({title:T[i%3][0],tag:['App Design','Branding','Mockup'][(i+(i>2?i%3:0))%3],img:`blog-${i+1}`}))
